services:
    app.admin.evento:
        class: AppBundle\Admin\EventoAdmin
        arguments: [~, AppBundle\Entity\Evento, AppBundle:EventoAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Evento }
        calls:
            - [ addChild, ["@app.admin.preinscriptos"]]

    app.admin.dptos_partidos:
        class: AppBundle\Admin\DptosPartidosAdmin
        arguments: [~, AppBundle\Entity\DptosPartidos, AppBundle:DptosPartidosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: DptosPartidos }
        public: true

    app.admin.estudios_alcanzados:
        class: AppBundle\Admin\EstudiosAlcanzadosAdmin
        arguments: [~, AppBundle\Entity\EstudiosAlcanzados, AppBundle:EstudiosAlcanzadosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EstudiosAlcanzados }
        public: true

    app.admin.evento_periodoprein:
        class: AppBundle\Admin\EventoPeriodopreinAdmin
        arguments: [~, AppBundle\Entity\EventoPeriodoprein, AppBundle:EventoPeriodopreinAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EventoPeriodoprein }
        public: true

    app.admin.localidades:
        class: AppBundle\Admin\LocalidadesAdmin
        arguments: [~, AppBundle\Entity\Localidades, AppBundle:LocalidadesAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Localidades }
        public: true

    app.admin.paises:
        class: AppBundle\Admin\PaisesAdmin
        arguments: [~, AppBundle\Entity\Paises, AppBundle:PaisesAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Paises }
        public: true

    app.admin.preinscriptos:
        class: AppBundle\Admin\PreinscriptosAdmin
        arguments: [~, AppBundle\Entity\Preinscriptos, AppBundle:PreinscriptosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Preinscriptos, show_in_dashboard: false }
        public: true

    app.admin.provincias:
        class: AppBundle\Admin\ProvinciasAdmin
        arguments: [~, AppBundle\Entity\Provincias, AppBundle:ProvinciasAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Provincias }
        public: true

    app.admin.tipo_finalizacion_estudios_alcanzados:
        class: AppBundle\Admin\TipoFinalizacionEstudiosAlcanzadosAdmin
        arguments: [~, AppBundle\Entity\TipoFinalizacionEstudiosAlcanzados, AppBundle:TipoFinalizacionEstudiosAlcanzadosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TipoFinalizacionEstudiosAlcanzados }
        public: true

    app.admin.evento_estados:
        class: AppBundle\Admin\EventoEstadosAdmin
        arguments: [~, AppBundle\Entity\EventoEstados, AppBundle:EventoEstadosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: EventoEstados }
        public: true

    app.admin.preinscriptos_estados:
        class: AppBundle\Admin\PreinscriptosEstadosAdmin
        arguments: [~, AppBundle\Entity\PreinscriptosEstados, AppBundle:PreinscriptosEstadosAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PreinscriptosEstados }
        public: true
